version: '3.8'

services:
  devnet:
    image: ${DOCKER_USERNAME}/geth:latest
    container_name: devnet
    ports:
      - "8545:8545"
      - "30303:30303"
    environment:
      - NETWORK_ID=1337
      - NODE_NAME=devnet-node
    command: >
      --networkid 1337
      --nodiscover
      --http
      --http.addr 0.0.0.0
      --http.port 8545

  blockscout:
    image: blockscout/blockscout:latest
    container_name: blockscout
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/blockscout
      ETHEREUM_JSONRPC_HTTP_URL: http://devnet:8545
      ETHEREUM_JSONRPC_WS_URL: ws://devnet:8546
      NETWORK: Devnet
      SUBNETWORK: Devnet
      COIN: ETH
    depends_on:
      - devnet
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blockscout
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: