name: Deploy Hardhat Project

on:
  pull_request:
    types: [closed]
    labels:
      - CI:Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub runner
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install project dependencies
    - name: Install dependencies
      run: npm install

    # Pull Docker image with predeployed contracts
    - name: Pull Docker image with predeployed contracts
      run: docker pull <your-docker-image>

    # Run Docker container with predeployed contracts
    - name: Run Docker container with predeployed contracts
      run: docker run -d --name predeployed-contracts <your-docker-image>

    # Run Hardhat tests inside the Docker container
    - name: Run Hardhat tests
      run: |
        docker exec predeployed-contracts bash -c "cd /path/to/your/hardhat/project && npx hardhat test"