name: Deploy Hardhat Project

on:
  pull_request:
    types: [closed]
    labels:
      - CI:Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub runner
    - name: Checkout repository
      uses: actions/checkout@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Pull Docker image with predeployed contracts
    - name: Pull Docker image with predeployed contracts
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/geth:latest

    # Run Docker container with predeployed contracts
    - name: Run Docker container with predeployed contracts
      run: docker run -d --name predeployed-contracts ${{ secrets.DOCKER_USERNAME }}/geth:latest

    # Run Hardhat tests inside the Docker container
    - name: Run Hardhat tests
      run: |
        docker exec predeployed-contracts bash -c "cd / && npx hardhat test"