name: Deploy Hardhat Project

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Check for CI:Deploy label
      id: check_label
      run: |
        labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
        echo "Labels: $labels"
        if ! echo "$labels" | grep -q "CI:Deploy"; then
          echo "Label CI:Deploy not found, skipping deployment."
          exit 1
        fi

    - name: Checkout repository
      if: steps.check_label.outcome == 'success'
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      if: steps.check_label.outcome == 'success'
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      if: steps.check_label.outcome == 'success'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      if: steps.check_label.outcome == 'success'
      run: |
        docker build -t your-dockerhub-username/hardhat-geth:latest .
        docker push your-dockerhub-username/hardhat-geth:latest

    - name: Run Hardhat tests in Docker container
      if: steps.check_label.outcome == 'success'
      run: |
        docker run --name predeployed-contracts -d your-dockerhub-username/hardhat-geth:latest
        docker exec predeployed-contracts sh -c "cd /app && npx hardhat test"